export const SKILL_LIBRARY = [
  "accounting",
  "adobe creative suite",
  "agile",
  "analysis",
  "analytics",
  "audit",
  "automation",
  "budgeting",
  "business development",
  "c",
  "c++",
  "cad",
  "campaign management",
  "communication",
  "content writing",
  "copywriting",
  "crm",
  "css",
  "customer service",
  "data analysis",
  "data visualization",
  "digital marketing",
  "economics",
  "excel",
  "figma",
  "finance",
  "financial modeling",
  "git",
  "graphic design",
  "html",
  "human resources",
  "java",
  "javascript",
  "leadership",
  "machine learning",
  "market research",
  "marketing",
  "microsoft office",
  "negotiation",
  "node.js",
  "operations",
  "photoshop",
  "power bi",
  "presentation",
  "problem solving",
  "product management",
  "project management",
  "public speaking",
  "python",
  "react",
  "recruitment",
  "research",
  "sales",
  "seo",
  "sql",
  "statistics",
  "strategy",
  "tableau",
  "teaching",
  "teamwork",
  "typescript",
  "ui design",
  "ux research",
  "writing"
] as const;

export const JD_SIGNAL_TERMS = [
  "power bi",
  "tableau",
  "excel",
  "sql",
  "python",
  "dashboard",
  "reporting",
  "stakeholder",
  "forecasting",
  "financial modeling",
  "crm",
  "seo",
  "campaign",
  "content",
  "research",
  "presentation",
  "leadership",
  "communication",
  "analysis",
  "automation",
  "project management"
] as const;

export const SECTION_ALIASES: Record<string, string[]> = {
  contact: ["email", "phone", "linkedin", "github", "portfolio"],
  summary: ["summary", "profile", "objective", "about"],
  experience: ["experience", "employment", "work history", "internship"],
  education: ["education", "degree", "university", "college", "school"],
  skills: ["skills", "technical skills", "core competencies", "tools"],
  projects: ["projects", "portfolio", "case studies"],
  achievements: ["achievements", "awards", "certifications", "publications"]
};
